// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hownsbjemcleccfpnwtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvd25zYmplbWNsZWNjZnBud3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDQzODMsImV4cCI6MjA2OTUyMDM4M30.gT0n8v0TQBHH627dl4v-7xUKLHtKx_6V1TxLnv-7ZYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});